/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estudio_beta;

import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Color.yellow;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Nico
 */

public class Interfaz_formato extends javax.swing.JFrame {
public String Usu1="Nicolas",Usu2="Amado",Usu3="ElMENCHO",contra1="Best",contra2="Fuentes12",contra3="Elespecial";
    /**
     * Creates new form Interfaz_formato
     */
    public Interfaz_formato() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        C = new javax.swing.JPanel();
        Ingresar = new javax.swing.JButton();
        OcultarUsU = new javax.swing.JButton();
        Contraseña = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        P_acceso = new javax.swing.JLabel();
        Pablo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        C.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar.setText("INGRESAR");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        C.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 250, -1));

        OcultarUsU.setText("LIMPIAR");
        OcultarUsU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcultarUsUActionPerformed(evt);
            }
        });
        C.add(OcultarUsU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, -1));

        Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContraseñaKeyTyped(evt);
            }
        });
        C.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, -1));

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioKeyTyped(evt);
            }
        });
        C.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel2.setText("CONTRASEÑA");
        C.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel3.setText("USUARIO");
        jLabel3.setToolTipText("");
        C.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        P_acceso.setBackground(new java.awt.Color(255, 255, 255));
        P_acceso.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        P_acceso.setText("PUNTO DE ACCESO");
        C.add(P_acceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        Pablo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pablo-escobar-6664780_1280.png"))); // NOI18N
        C.add(Pablo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1490, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Borrar(){
        Usuario.setText(null);
        Contraseña.setText(null);
    }
    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaKeyTyped
        // Llave creada para controlar el teclado
        
         if(Contraseña.getText().length()>=10 ){
             evt.consume();//No permite que se digiten mas caracteres
        }
         
    }//GEN-LAST:event_ContraseñaKeyTyped

    private void UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyTyped
        // TODO add your handling code here:
        if(Usuario.getText().length()>=8){
            evt.consume();//No permite que se digiten mas caracteres
        }
    }//GEN-LAST:event_UsuarioKeyTyped

    private void OcultarUsUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcultarUsUActionPerformed
        // TODO add your handling code here:
       Borrar();
    }//GEN-LAST:event_OcultarUsUActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        if((Usuario.getText().equals(Usu1)&&(Contraseña.getText().equals(contra1)))||(Usuario.getText().equals(Usu2)&&Contraseña.getText().equals(contra2))||(Usuario.getText().equals(Usu3)&&Contraseña.getText().equals(contra3))){//
             Proceso a = new Proceso();        
         a.setVisible(true);
        }else{           
            JOptionPane.showMessageDialog(null,"Contraseña o usuario Incorrecto".toUpperCase(),"Error Message",JOptionPane.ERROR_MESSAGE);    
        }
        
    }//GEN-LAST:event_IngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_formato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_formato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_formato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_formato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_formato().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel C;
    private javax.swing.JTextField Contraseña;
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton OcultarUsU;
    private javax.swing.JLabel P_acceso;
    private javax.swing.JLabel Pablo;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
