/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Nico
 */
public class k extends javax.swing.JFrame {

    /**
     * Creates new form k
     */
    private c log =new c();
    private void SetCards(){
       
    }
    public k() {    
        initComponents();
        ArreglarCartas();
    }
    private c llamar =new c();
    public void ArreglarCartas(){
         int []numbers =log.c();
        B1.setDisabledIcon(new ImageIcon(getClass().getResource("/Img/I"+numbers[0]+".jpg")));
        B2.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[1]+".jpg")));
        B3.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[2]+".jpg")));
        B4.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[3]+".jpg")));
        B5.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[4]+".jpg")));
        B6.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[5]+".jpg")));
        B7.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[6]+".jpg")));
        B8.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[7]+".jpg")));
        B9.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[8]+".jpg")));
        B10.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[9]+".jpg")));
        B11.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[10]+".jpg")));
        B12.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[11]+".jpg")));
        B13.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[12]+".jpg")));
        B14.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[13]+".jpg")));
        B15.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[14]+".jpg")));
        B16.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[15]+".jpg")));
        B17.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[16]+".jpg")));
        B18.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[17]+".jpg")));
        B19.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[18]+".jpg")));
        B20.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[19]+".jpg")));
        B21.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[20]+".jpg")));
        B22.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[21]+".jpg")));
        B23.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[22]+".jpg")));
        B24.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[23]+".jpg")));
        B25.setDisabledIcon(new ImageIcon(getClass().getResource("Img/I"+numbers[24]+".jpg"))); 
    }


        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        B13 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B24 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B20 = new javax.swing.JButton();
        B23 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B19 = new javax.swing.JButton();
        B17 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        B18 = new javax.swing.JButton();
        B22 = new javax.swing.JButton();
        B25 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 80, 90));

        B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });
        jPanel1.add(B12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 80, 90));

        B24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 80, 90));

        B21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B21.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 80, 90));

        B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 80, 90));

        B20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B20ActionPerformed(evt);
            }
        });
        jPanel1.add(B20, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 80, 90));

        B23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B23ActionPerformed(evt);
            }
        });
        jPanel1.add(B23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 80, 90));

        B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });
        jPanel1.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 80, 90));

        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jPanel1.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 80, 90));

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 80, 90));

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 80, 90));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 80, 90));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 80, 90));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 80, 90));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 80, 90));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 80, 90));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B1.setDisabledIcon(null);
        B1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 80, 90));

        B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 80, 90));

        B19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B19, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 80, 90));

        B17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B17ActionPerformed(evt);
            }
        });
        jPanel1.add(B17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 80, 90));

        B15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 80, 90));

        B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 80, 90));

        B18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 80, 90));

        B22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        B22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B22ActionPerformed(evt);
            }
        });
        jPanel1.add(B22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 80, 90));

        B25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/red-2892235_640.png"))); // NOI18N
        B25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/rojo.png"))); // NOI18N
        jPanel1.add(B25, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 80, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase/moon-31665_1280.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_B4ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B22ActionPerformed

    private void B17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B17ActionPerformed

    private void B20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B20ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B10ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B23ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_B12ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(k.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(k.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(k.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(k.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new k().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B13;
    private javax.swing.JButton B14;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B17;
    private javax.swing.JButton B18;
    private javax.swing.JButton B19;
    private javax.swing.JButton B2;
    private javax.swing.JButton B20;
    private javax.swing.JButton B21;
    private javax.swing.JButton B22;
    private javax.swing.JButton B23;
    private javax.swing.JButton B24;
    private javax.swing.JButton B25;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
