
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ESTUDIANTE22
 */
public class Clips extends javax.swing.JFrame {

    /**
     * Creates new form Clips
     */
    public Clips() {
        initComponents();
    }
    public String Blinding ="Blinding Lights";
    public String Side ="Side to Side";
        public String Moonlight ="Moonlight Sonata";
    public String Morning ="Morning mood";
    public String sol="Morning mood";
    public String ojitos ="Ojitos chiquitos";
    public String Killka="Killka";
    public String ILLUSIONS="ILLUSIONS";
    public String Coma ="Coma white";
    public String Tourniquet="Tourniquet";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        boton_buscar_clips = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bcomprar = new javax.swing.JButton();
        balquilar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setForeground(new java.awt.Color(255, 204, 51));

        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("CATEGORIAS DE CLIPS");

        boton_buscar_clips.setBackground(new java.awt.Color(0, 0, 255));
        boton_buscar_clips.setForeground(new java.awt.Color(255, 204, 51));
        boton_buscar_clips.setText("Buscar");
        boton_buscar_clips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar_clipsActionPerformed(evt);
            }
        });

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        bcomprar.setBackground(new java.awt.Color(0, 0, 255));
        bcomprar.setForeground(new java.awt.Color(255, 204, 51));
        bcomprar.setText("Comprar");

        balquilar.setBackground(new java.awt.Color(0, 0, 255));
        balquilar.setForeground(new java.awt.Color(255, 204, 51));
        balquilar.setText("Alquilar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(254, 254, 254)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bcomprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(balquilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(242, 242, 242)
                            .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(boton_buscar_clips))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_buscar_clips))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bcomprar)
                .addGap(18, 18, 18)
                .addComponent(balquilar)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setText("Categorias");

        jMenu3.setForeground(new java.awt.Color(0, 0, 255));
        jMenu3.setText("Pop");

        jMenuItem1.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem1.setText("Blinding Lights");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem2.setText("Side to Side");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 51, 255));
        jMenu4.setText("Musica clasica");

        jMenuItem3.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem3.setText("Moonlight Sonata");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem4.setText("Morning mood");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenu1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(0, 0, 255));
        jMenu5.setText("Reggaeton");

        jMenuItem5.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem5.setText("Salio el sol");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem6.setText("Ojitos chiquiticos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenu1.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(0, 51, 255));
        jMenu6.setText("Rock");

        jMenuItem7.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem7.setText("Coma white");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem8.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem8.setText("Tourniquet");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenu1.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(0, 51, 255));
        jMenu7.setText("Phonk");

        jMenuItem9.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem9.setText("Killka");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem10.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem10.setText("ILLUSIONS");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         buscador.setText(""+Blinding);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         buscador.setText(""+ILLUSIONS);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
                buscador.setText(""+ojitos);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        buscador.setText(""+Morning);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        buscador.setText(""+Side);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        buscador.setText(""+Moonlight);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
                buscador.setText(""+sol);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
                buscador.setText(""+Coma);

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
                buscador.setText(""+Tourniquet);

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
                        buscador.setText(""+Killka);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void boton_buscar_clipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar_clipsActionPerformed
        // TODO add your handling code here:
        if (buscador.getText().equals(Blinding)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/The_weeknd.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }
         if (buscador.getText().equals(Side)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/side.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }
         if (buscador.getText().equals(Moonlight)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/sonata.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }
         if (buscador.getText().equals(Morning)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/Morning.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }
          if (buscador.getText().equals(sol)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/sol.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }
          
        if (buscador.getText().equals(ojitos)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/sol.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }  
         if (buscador.getText().equals(Killka)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/killka.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }  
          if (buscador.getText().equals(ILLUSIONS)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/ILLUSIONS.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }  
          
           if (buscador.getText().equals(Coma)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/coma_white.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }  
               if (buscador.getText().equals(Tourniquet)){

            
            rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/tourniquet.png");
         bcomprar.setEnabled(true);
        balquilar.setEnabled(true);
            
        }  
               
           
           
    }//GEN-LAST:event_boton_buscar_clipsActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if (buscador.getText().equals(Blinding )){

            
            
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=fHI8X4OXluQ"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
        }
            
            if (buscador.getText().equals(Side)){

            
            
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=SXiSVQZLje8"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
          if (buscador.getText().equals(Moonlight)){

            
            
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=TVDREzBijRI"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
             if (buscador.getText().equals(Morning)){

            
            
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=-rh8gMvzPw0"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
             if (buscador.getText().equals(sol)){
                 
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=Z-3su2ov8Vg"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
       
              if (buscador.getText().equals(ojitos)){
                 
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=HTOzVI3C8hQ"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
               if (buscador.getText().equals(Killka)){
                 
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=R7PZvI3QZoc"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
                 if (buscador.getText().equals(ILLUSIONS)){
                 
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=WJpTZmaWv2A"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
                 
                 if (buscador.getText().equals(Coma)){
                 
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=QQPJYnr48yU"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
                  
                 if (buscador.getText().equals(Tourniquet)){
                 
            try{
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=MmfQ7gSaJgM"));
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "error");
            }
            
        }
            
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balquilar;
    private javax.swing.JButton bcomprar;
    private javax.swing.JButton boton_buscar_clips;
    private javax.swing.JTextField buscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
