
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Nico
 */
public class Registros extends javax.swing.JFrame {

    /**
     * Creates new form Registros
     */
    public Registros() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    public int cedula, terror = 10000, romance = 8000, drama = 9500, comedia = 7800, tel_fijo, tel_cel, cantidad, vector_info;//,cantidad_de_clientes=Integer.parseInt(JOptionPane.showInputDialog("CANTIDAD DE CLIENTES"))//posible arreglo
    public String  costototal="100000",costototal2="80000",costototal3="40000",costototal4="99000",pregunta_prestamo, total, codigo, nombre_pelicula, Genero_pelicula, P_principal, Opc_VoP, pregunta_personaje_2, P_Principal_2, nombre, apellido, direccion, barrio, genero, genero_c, tel_fijo_c, conversion_de_cedula, conversion_de_tel_cel, conversion_de_tel_fijo, infor, dias_prestados;
    public String[] v_info;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        Genero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        Barrio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Telf_fijo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Celular = new javax.swing.JTextField();
        Impresora = new javax.swing.JTextField();
        Info = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Cliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Mostrarinfo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));

        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("CEDULA");

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("NOMBRE");

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("APELLIDO");

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("GENERO");

        jLabel6.setText("DIRECCION");

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });

        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("BARRIO");

        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });

        Barrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarrioActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("TELEFONO FIJO");

        Telf_fijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telf_fijoActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("TELEFONO CEL");

        Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelularActionPerformed(evt);
            }
        });

        Impresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpresoraActionPerformed(evt);
            }
        });

        Info.setBackground(new java.awt.Color(0, 0, 255));
        Info.setForeground(new java.awt.Color(255, 204, 51));
        Info.setText("REGISTRARSE");
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("CLIENTE");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("REGISTRO");

        Mostrarinfo.setBackground(new java.awt.Color(0, 0, 255));
        Mostrarinfo.setForeground(new java.awt.Color(255, 204, 51));
        Mostrarinfo.setText("MOSTRAR INFORMACION");
        Mostrarinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarinfoActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setForeground(new java.awt.Color(255, 204, 51));
        jButton3.setText("CIERRA SESION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel1.setText("COSTO TOTAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(Mostrarinfo)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(230, 230, 230))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton3)
                .addGap(96, 96, 96)
                .addComponent(Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mostrarinfo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(Salir))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Info)
                                .addGap(18, 18, 18)
                                .addComponent(Impresora, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Genero, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(Barrio)
                                .addComponent(Telf_fijo)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(Celular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telf_fijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Info)
                    .addComponent(Impresora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(237, 237, 237))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
        Apellido.setVisible(true);
        Apellido.setText(apellido);
    }//GEN-LAST:event_ApellidoActionPerformed

    private void ImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpresoraActionPerformed
        // TODO add your handling code here:
        muestra();
        //Impresora.setText("Cedula:"+Cedula+"\n"+"Nombre:"+Nombre);
    }//GEN-LAST:event_ImpresoraActionPerformed

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        // TODO add your handling code here:
        Informacion();
    }//GEN-LAST:event_InfoActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
        Cedula.setVisible(true);
        Cedula.setText(conversion_de_cedula);

    }//GEN-LAST:event_CedulaActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
        Nombre.setVisible(true);
        Nombre.setText(nombre);
    }//GEN-LAST:event_NombreActionPerformed

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
        // TODO add your handling code here:
        Genero.setVisible(true);
        Genero.setText(genero);
    }//GEN-LAST:event_GeneroActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
        Direccion.setVisible(true);
    }//GEN-LAST:event_DireccionActionPerformed

    private void BarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarrioActionPerformed
        // TODO add your handling code here:
        Barrio.setVisible(true);
    }//GEN-LAST:event_BarrioActionPerformed

    private void Telf_fijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telf_fijoActionPerformed
        // TODO add your handling code here:
        Telf_fijo.setVisible(true);
    }//GEN-LAST:event_Telf_fijoActionPerformed

    private void CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelularActionPerformed
        // TODO add your handling code here:
        Celular.setVisible(true);
    }//GEN-LAST:event_CelularActionPerformed

    private void MostrarinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarinfoActionPerformed
        // TODO add your handling code here:
        muestra();
    }//GEN-LAST:event_MostrarinfoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Inicio X = new Inicio();
        X.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed
    /* public void Entrada(){
        
    }*/
    /*public void Clientes_Deudores() {

        String boton;
        boton = JOptionPane.showInputDialog(null, "Clientes Sancionados\n1.Categoria o Genero\n2.Persona\n3.Total");
        switch (boton) {
            case "clientes sancionados":
                JOptionPane.showMessageDialog(null, "Este es el titulo, pedazo de mono");
                break;
            case "Genero","Categoria","1":
                JOptionPane.showMessageDialog(null, "Terror:502.000.000 " + "\nRomance:60.000.000 \n " + "Drama:  40.050.000 \n" + "Comedia:500.000.500\n " + "Documentales:2.200.000 ");
                break;
            case "Persona","Cliente","2":
                JOptionPane.showMessageDialog(null, "Maria Juana Mesa $2.000.000  cedula:303020092 direccion:casa_1  barrio:a \nEl chapo Guzman $500.000.000   cedula:200.897.564  direccion:casa_2  barrio:b" + "\nPablo Escobar  $20.000.000  cedula:390.090.282  direccion:casa_3  barrio:c\nGilberto Rodriguez Orejuela $40.000.000  cedula:347.890.728  direccion:casa_4 barrio:d\nElizabeth Taylor  $50.000  cedula:678.289.920 direccion:casa_5 barrio:e \nAmado Carrillo Fuentes $500.000 cedula:562.293.209 direccion:casa_6 barrio:f\nCanserbero Gonzales $500 cedula:256.733.678  direccion: casa_7 barrio:g\nNemesio Oseguera Cervantes $500.000.000  cedula:238.890.892 direccion:casa_8  barrio:h\nRoller Smith $200.000  cedula:367.289.019  direccion:casa_9 barrio:i \nHugo Chavez  $2.000.000 cedula:679.093.278  direccion:casa 10  barrio:j");
                break;
            case "Total","3":
                JOptionPane.showMessageDialog(null, "$1.064.750.500");
                break;
        }
    }
*/
    /*  public void Cantidad (){
        for (int i = 0; i <cantidad_de_clientes ; i++) {
            
            
        }
      
    }*/
    public void Informacion() {

        // cantidad = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de clientes"));
        //  for (int i = 0+1; i < cantidad; i++) {
        Nombre.setText(null);
        nombre = JOptionPane.showInputDialog("Digite su nombre");
        Impresora.setText("Nombre:" + nombre + "\n");
        Nombre.setText(nombre + "\n");
        Apellido.setText(null);
        Genero.setText(null);
        Cedula.setText(null);
        Direccion.setText(null);
        Barrio.setText(null);
        Telf_fijo.setText(null);
        Celular.setText(null);
        //Cliente.setText(i + " ");
        // System.out.println("cliente: " + i);
        System.out.print("Nombre:" + nombre + " ");
        apellido = JOptionPane.showInputDialog("Digite su apellido");
        Impresora.setText("Apellido:" + apellido);
        Apellido.setText(apellido);
        System.out.println("Apellido:" + apellido + " ");
        cedula = Integer.parseInt(JOptionPane.showInputDialog("Digite su cedula"));
        conversion_de_cedula = cedula + "";
        Impresora.setText("Cedula:" + conversion_de_cedula);
        Cedula.setText(conversion_de_cedula);
        System.out.println("Cedula:" + conversion_de_cedula + " ");
        direccion = JOptionPane.showInputDialog("Digite su direccion");
        Impresora.setText("Direccion:" + direccion);
        Direccion.setText(direccion);
        System.out.println("Direccion:" + direccion + " ");
        barrio = JOptionPane.showInputDialog("Digite su barrio");
        Impresora.setText("Barrio:" + barrio);
        Barrio.setText(barrio);
        System.out.println("Barrio:" + barrio + " ");
        tel_cel = Integer.parseInt(JOptionPane.showInputDialog("Digite su telefono celular"));
        conversion_de_tel_cel = tel_cel + "";
        Impresora.setText("Celular:" + conversion_de_tel_cel);
        Celular.setText(conversion_de_tel_cel);
        System.out.println("Celular:" + conversion_de_tel_cel + " ");
        genero_c = JOptionPane.showInputDialog("¿Desea responder su genero?\n1.si\n2.no");

        switch (genero_c) {
            case "si":
                genero = JOptionPane.showInputDialog("¿cual es su Genero?");
                Impresora.setText("Genero:" + genero);
                Genero.setText(genero);
                System.out.println("Genero:" + genero + " ");
                break;
            case "no":
                Impresora.setText("Genero no responde");
                Genero.setText("no responde");
                System.out.println("Genero no responde" + " ");
                break;
        }
        tel_fijo_c = JOptionPane.showInputDialog("¿Tiene telefono fijo?\n1.si\n2.no");
        switch (tel_fijo_c) {
            case "si":
                tel_fijo = Integer.parseInt(JOptionPane.showInputDialog("Numero de telefono"));
                conversion_de_tel_fijo = tel_fijo + "";
                Impresora.setText("Telefono Fijo:" + conversion_de_tel_fijo);
                Telf_fijo.setText(conversion_de_tel_fijo);
                System.out.println("Telefono Fijo:" + conversion_de_tel_fijo);
                break;
            case "no":
                Impresora.setText("Telefono Fijo no tiene");
                Telf_fijo.setText("no tiene");
                System.out.println("Telefono Fijo no tiene");
                break;
        }
        Opc_VoP = JOptionPane.showInputDialog("1.comprar  \n2.Rentar o prestar");
        switch (Opc_VoP) {
            case "comprar","1":
                codigo = JOptionPane.showInputDialog("Codigo:\n1.Terror \n2.Romance \n3.Drama \n4.Comedia");
                System.out.println("Codigo" + codigo);
                Genero_pelicula = JOptionPane.showInputDialog("Genero de la pelicula \n1.Terror \n2.Romance \n3.Drama \n4.Comedia");
                System.out.println("Genero de la pelicula" + Genero_pelicula);
                switch (Genero_pelicula) {
                    case "1","Terror","terror":
                        nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Terror");
                        System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                        P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                        System.out.println("Personaje principal:" + P_principal);
                        pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                        switch (pregunta_personaje_2) {
                            case "si":
                                P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                System.out.print("  " + P_Principal_2);  
                                costo.setText(costototal);
                                break;
                        }
                        break;
                    case "2","Romance","romance":
                        nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Romance");
                        System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                        P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                        System.out.println("Personaje principal:" + P_principal);
                        pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                        switch (pregunta_personaje_2) {
                            case "si":
                                P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                System.out.print("  " + P_Principal_2);
                                costo.setText(costototal2);
                                break;
                        }
                        break;
                    case "3","Drama","drama":
                        nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Drama");
                        System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                        P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                        System.out.println("Personaje principal:" + P_principal);
                        pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                        switch (pregunta_personaje_2) {
                            case "si":
                                P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                System.out.print("  " + P_Principal_2);
                                costo.setText(costototal3);
                                break;
                        }
                        break;
                    case "4","Comedia","comedia":
                        nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Comedia");
                        System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                        P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                        System.out.println("Personaje principal:" + P_principal);
                        pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                        switch (pregunta_personaje_2) {
                            case "si":
                                P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                System.out.print("  " + P_Principal_2);
                                costo.setText(costototal4);
                                break;
                        }
                        break;
                    case "2.","prestar":
                        codigo = JOptionPane.showInputDialog("Codigo:\n1.Terror \n2.Romance \n3.Drama \n4.Comedia");
                        System.out.println("Codigo" + codigo);
                        Genero_pelicula = JOptionPane.showInputDialog("Genero de la pelicula \n1.Terror \n2.Romance \n3.Drama \n4.Comedia");
                        System.out.println("Genero de la pelicula" + Genero_pelicula);
                        switch (Genero_pelicula) {
                            case "1","Terror","terror":
                                nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Terror");
                                System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                                P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                                System.out.println("Personaje principal:" + P_principal);
                                pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                                switch (pregunta_personaje_2) {
                                    case "si":
                                        P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                        System.out.print("  " + P_Principal_2);
                                        costo.setText("$20.000");
                                        break;
                                }
                                dias_prestados = JOptionPane.showInputDialog("Cuantos dias quiere prestar la pelicula");
                                break;
                            case "2","Romance","romance":
                                nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Romance");
                                System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                                P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                                System.out.println("Personaje principal:" + P_principal);
                                pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                                switch (pregunta_personaje_2) {
                                    case "si":
                                        P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                        System.out.print("  " + P_Principal_2);
                                        costo.setText("$16.000");
                                        break;
                                }
                                break;
                            case "3","Drama","drama":
                                nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Drama");
                                System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                                P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                                System.out.println("Personaje principal:" + P_principal);
                                pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                                switch (pregunta_personaje_2) {
                                    case "si":
                                        P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                        System.out.print("  " + P_Principal_2);
                                        costo.setText("$8.000");
                                        break;
                                }

                                break;
                            case "4","Comedia","comedia":
                                nombre_pelicula = JOptionPane.showInputDialog("Nombre de la pelicula de Comedia");
                                System.out.println("Nombre de la pelicula:" + nombre_pelicula);
                                P_principal = JOptionPane.showInputDialog("Personaje principal de la pelicula");
                                System.out.println("Personaje principal:" + P_principal);
                                pregunta_personaje_2 = JOptionPane.showInputDialog("¿Tiene otro personaje Principal? \n1.si \n2.no");
                                switch (pregunta_personaje_2) {
                                    case "si":
                                        P_Principal_2 = JOptionPane.showInputDialog("personaje Principal 2");
                                        System.out.print("  " + P_Principal_2);
                                        costo.setText("$19.800");
                                        break;
                                }
                                break;
                        }

                        infor = "Nombre: " + nombre + "\nApellido: " + apellido + "\n Cedula:" + conversion_de_cedula + "\nDireccion: " + direccion + "\nBarrio: " + barrio + "\nCelular: " + conversion_de_tel_cel + "\nGenero: " + genero + "\nTelefono fijo:" + conversion_de_tel_fijo + "\nCodigo:" + codigo + "\nGenero:" + Genero_pelicula + "\nPelicula:" + nombre_pelicula + "\nPersonaje principal:" + P_principal + "+P_Principal_2"+"Costo:"+costo;
                        //"Cliente" + i +

                        String[] v_info = {infor};
                        //JOptionPane.showMessageDialog(null, v_info);
                        JOptionPane.showMessageDialog(null, infor);
                    //se me olvido poner un saul para costo total de los vender
                    }
        }
        //}
    }

    /*public void print(){
        
    }*/
    public void muestra() {
        //Arreglar 

        /*for (int i = 0; i < cantidad; i++) {
           Impresora.setText("Nombre: "+nombre+"\nApellido: "+apellido+"\n Cedula:"+conversion_de_cedula+"\nDireccion: "+direccion+"\nBarrio: "+barrio+"\nCelular: "+conversion_de_tel_cel+"\nGenero: "+genero+"Telefono fijo:"+conversion_de_tel_fijo);
            //crear es un boton
            
        }*/
        // JOptionPane.showMessageDialog(null,"Nombre: "+nombre+"\nApellido: "+apellido+"\n Cedula:"+conversion_de_cedula+"\nDireccion: "+direccion+"\nBarrio: "+barrio+"\nCelular: "+conversion_de_tel_cel+"\nGenero: "+genero+"Telefono fijo:"+conversion_de_tel_fijo);
        JOptionPane.showMessageDialog(null, infor);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Barrio;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Celular;
    private javax.swing.JTextField Cliente;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Genero;
    private javax.swing.JTextField Impresora;
    private javax.swing.JButton Info;
    private javax.swing.JButton Mostrarinfo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField Telf_fijo;
    private javax.swing.JTextField costo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
